In [62]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
from keras.preprocessing.image import ImageDataGenerator
import numpy as np
from tensorflow.keras.preprocessing import image
import warnings
warnings.filterwarnings("ignore")

In [24]:
model = Sequential()

#1ª camada
model.add(Conv2D(64, (3,3), input_shape=(64,64,3), activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))

#2ª camada
model.add(Conv2D(64, (3,3), input_shape=(64,64,3), activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(units=128, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(units=128, activation="relu"))
model.add(Dropout(0.2))

model.add(Dense(units=1, activation="sigmoid"))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [25]:
gerador_treinamento = ImageDataGenerator(rescale=1./255, rotation_range=7, horizontal_flip=True, shear_range=0.2, height_shift_range=0.07, zoom_range=0.2)
gerador_teste = ImageDataGenerator(rescale=1./255)

In [26]:
base_treinamento = gerador_treinamento.flow_from_directory("C:\\Users\\user\\Data Science\\banco_dados\\datasets\\dataset\\dataset\\training_set", 
                                                           target_size=(64,64),
                                                           batch_size=32,
                                                           class_mode="binary")

Found 4000 images belonging to 2 classes.


In [35]:
100//10

In [27]:
base_teste = gerador_teste.flow_from_directory("C:\\Users\\user\\Data Science\\banco_dados\\datasets\\dataset\\dataset\\test_set", 
                                                           target_size=(64,64),
                                                           batch_size=32,
                                                           class_mode="binary")

Found 1000 images belonging to 2 classes.


In [38]:
model.fit(base_treinamento, 
          steps_per_epoch=len(base_treinamento)//32,
          epochs=1000,
          validation_data = base_teste,
          validation_steps= len(base_teste)//32)

Epoch 1/1000
3/3 [==============================] - 2s 560ms/step - loss: 0.7719 - accuracy: 0.5729 - val_loss: 0.6237 - val_accuracy: 0.6250
Epoch 2/1000
3/3 [==============================] - 1s 509ms/step - loss: 0.5643 - accuracy: 0.6875 - val_loss: 0.5814 - val_accuracy: 0.6562
Epoch 3/1000
3/3 [==============================] - 1s 475ms/step - loss: 0.5260 - accuracy: 0.7188 - val_loss: 0.6529 - val_accuracy: 0.6250
Epoch 4/1000
3/3 [==============================] - 1s 521ms/step - loss: 0.6018 - accuracy: 0.6667 - val_loss: 0.7009 - val_accuracy: 0.5312
Epoch 5/1000
3/3 [==============================] - 1s 499ms/step - loss: 0.5412 - accuracy: 0.7396 - val_loss: 0.6938 - val_accuracy: 0.6562
Epoch 6/1000
3/3 [==============================] - 1s 478ms/step - loss: 0.6038 - accuracy: 0.6562 - val_loss: 0.5415 - val_accuracy: 0.6875
Epoch 7/1000
3/3 [==============================] - 1s 526ms/step - loss: 0.6248 - accuracy: 0.6667 - val_loss: 0.6530 - val_accuracy: 0.7188
Epoch 

In [81]:
# Vamos pegar um exemplo para classificar:
imagem_teste_gato = keras.utils.load_img("C:\\Users\\user\\Data Science\\banco_dados\\datasets\\dataset\\dataset\\test_set\\gato\\cat.3500.jpg", 
                              target_size=(64,64)) 


In [82]:
imagem_teste_gato = image.img_to_array(imagem_teste_gato)

In [83]:
# Normalizando
imagem_teste_gato /= 255

In [84]:
imagem_teste_gato

array([[[0.76862746, 0.7647059 , 0.7882353 ],
        [0.7647059 , 0.7607843 , 0.78431374],
        [0.81960785, 0.8156863 , 0.8392157 ],
        ...,
        [0.7490196 , 0.7372549 , 0.7647059 ],
        [0.75686276, 0.74509805, 0.77254903],
        [0.7411765 , 0.7294118 , 0.75686276]],

       [[0.8       , 0.79607844, 0.81960785],
        [0.80784315, 0.8039216 , 0.827451  ],
        [0.7607843 , 0.75686276, 0.78039217],
        ...,
        [0.7529412 , 0.7411765 , 0.76862746],
        [0.77254903, 0.7607843 , 0.7882353 ],
        [0.73333335, 0.72156864, 0.7490196 ]],

       [[0.76862746, 0.7647059 , 0.7882353 ],
        [0.76862746, 0.7647059 , 0.7882353 ],
        [0.75686276, 0.7529412 , 0.7764706 ],
        ...,
        [0.7490196 , 0.7372549 , 0.7647059 ],
        [0.7411765 , 0.7294118 , 0.75686276],
        [0.69803923, 0.6862745 , 0.7137255 ]],

       ...,

       [[0.98039216, 0.98039216, 0.98039216],
        [0.9764706 , 0.9764706 , 0.9764706 ],
        [0.9882353 , 0

In [85]:
imagem_teste_gato = np.expand_dims(imagem_teste_gato, axis=0)

In [87]:
y_pred_cat = model.predict(imagem_teste_gato)

1/1 [==============================] - 0s 22ms/step


In [88]:
y_pred_cat

array([[0.9996083]], dtype=float32)

In [76]:
# Com 0.9996 temos um gato
base_treinamento.class_indices

{'cachorro': 0, 'gato': 1}

In [89]:
#Agora vamos fazer um teste com uma fotografia de cachorro
imagem_teste_dog = keras.utils.load_img("C:\\Users\\user\\Data Science\\banco_dados\\datasets\\dataset\\dataset\\test_set\\cachorro\\dog.3500.jpg", 
                              target_size=(64,64)) 

In [90]:
imagem_teste_dog = image.img_to_array(imagem_teste_dog)

In [91]:
# Normalizando
imagem_teste_dog /= 255

In [92]:
imagem_teste_dog

array([[[0.47058824, 0.49019608, 0.46666667],
        [0.41568628, 0.43529412, 0.4117647 ],
        [0.44705883, 0.46666667, 0.44313726],
        ...,
        [0.22745098, 0.16470589, 0.11372549],
        [0.25490198, 0.14901961, 0.11372549],
        [0.27450982, 0.13725491, 0.11372549]],

       [[0.4117647 , 0.43137255, 0.40784314],
        [0.5058824 , 0.5254902 , 0.5019608 ],
        [0.5254902 , 0.54509807, 0.52156866],
        ...,
        [0.23529412, 0.15686275, 0.11372549],
        [0.25882354, 0.16470589, 0.1254902 ],
        [0.27058825, 0.15686275, 0.1254902 ]],

       [[0.49411765, 0.5137255 , 0.49019608],
        [0.5137255 , 0.53333336, 0.50980395],
        [0.4627451 , 0.48235294, 0.45882353],
        ...,
        [0.2509804 , 0.15686275, 0.11764706],
        [0.2509804 , 0.16470589, 0.12156863],
        [0.24705882, 0.16078432, 0.11764706]],

       ...,

       [[0.61960787, 0.64705884, 0.7176471 ],
        [0.7372549 , 0.7764706 , 0.8156863 ],
        [0.72156864, 0

In [93]:
imagem_teste_dog = np.expand_dims(imagem_teste_dog, axis=0)

In [96]:
y_pred_dog = model.predict(imagem_teste_dog)

1/1 [==============================] - 0s 27ms/step


In [97]:
y_pred_dog

array([[0.11356771]], dtype=float32)

In [95]:
# Com 0.1135 temos um  cachorro
base_treinamento.class_indices

{'cachorro': 0, 'gato': 1}